version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.total_shards_per_node=1000
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
  app_production:
    container_name: docker-spring-boot-production
    profiles: ["production"]
    environment:
      - SPRING_PROFILES_ACTIVE=production
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    restart: on-failure
  app_test:
    container_name: docker-spring-boot-test
    profiles: ["test"]
    environment:
      - SPRING_PROFILES_ACTIVE=test
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    restart: on-failure
networks:
  esnet:
    driver: bridge
volumes:
  esdata:
    driver: local
